#!/bin/zsh
PARAMS="$@"
CMD="cd /src && RAILS_ENV=$RAILS_ENV DISCOURSE_DEV_ALLOW_ANON_TO_IMPERSONATE=$DISCOURSE_DEV_ALLOW_ANON_TO_IMPERSONATE LOAD_PLUGINS=$LOAD_PLUGINS $PARAMS"
sudo docker exec -it -u discourse:discourse $NAME /bin/bash -c "$CMD"
