#!/bin/bash

bundle exec rubocop --parallel
e eslint app/assets/javascripts test/javascripts
e eslint --ext .es6 app/assets/javascripts test/javascripts plugins
e prettier --list-different "app/assets/stylesheets/**/*.scss"
