#!/bin/bash

RAILS_ENV=test

if [ "$1" = "coverage" ] || [ "$1" = "all" ]
then
  rake SIMPLECOV=1 plugin:spec[$2]
fi

if [ "$1" = "spec" ]
then
  rake plugin:spec[$2]
fi

if [ "$1" = "qunit" ] || [ "$1" = "all" ]
then
  rake plugin:qunit[$2]
fi
