#!/bin/zsh
PARAMS="$@"
if [[ $# = 1 ]] && [[ "$1" =~ "s" ]];
then
  PARAMS="$PARAMS -b 0.0.0.0"
fi

CMD="RUBY_GLOBAL_METHOD_CACHE_SIZE=131072 LD_PRELOAD=/usr/lib/libjemalloc.so RACK_HANDLER=puma rails $PARAMS"
e $CMD
